### ISSUE TITLE
Will need further discussions for integrating the validation attributes

### ISSUE THREAD

**Issue by geodanila** [tanghel/tg-framework#1]
Had a look at the EditFieldBase class in order to figure out where the Binding was created. Not extremely happy with the current implementation. We should meet up and discuss this further :) 

:+1:

**Comment by tanghel** [comment]
Ay ay sir :) I don'tlike the implementation either. How about tomorrow?

**Comment by geodanila** [comment]
Let's meet up Wednesday if you're free.

**Comment by geodanila** [comment]
All is well :+1:
